name: Build and Publish
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@werty1st'
          always-auth: true

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Build package
        run: yarn build
      
      # Only run publish on push to master or release
      - name: Publish package
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' || github.event_name == 'release'
        run: |
          # Change to package directory
          cd cdk-multi-profile-plugin
          # Make sure package name includes the scope
          echo "Checking package.json configuration..."
          cat package.json
          # Publish package
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}